Registration/ISD
football-it-league-dnipro/football-it-dp-ua pull request #10
Opened 2019-09-17 10:58 UTC by kirill-dnepr

Заявка команды ISD.

2019-09-17 11:04 UTC, steamhammer submitted a review, later dismissed

2019-09-17 17:59 UTC, anton-kochev requested changes
List of players in `squad.md` should be provided in the alphabetical order

2019-09-20 09:54 UTC, anton-kochev requested changes

2019-09-20 09:54 UTC, anton-kochev commented on applications/ISD/squad.md
> +`8` [**Золотаренко** Михайло](/players/zolotarenko.mykhailo.19880229.png) `/1988-02-29/` SoftServe
Фотографии должны быть в формате `jpeg`

2019-09-20 09:56 UTC, anton-kochev commented
Заявочные материалы приняты. Фотографии приняты

2019-09-20 20:37 UTC, steamhammer submitted a review, later dismissed

2019-09-23 12:25 UTC, anton-kochev approved these changes

2019-09-23 12:26 UTC, anton-kochev requested changes
Фотографии должны быть в jpeg формате

2019-09-23 14:31 UTC, anton-kochev approved these changes

2019-09-23 14:31 UTC, merged