keyua registration
football-it-league-dnipro/football-it-dp-ua pull request #11
Opened 2019-09-17 11:27 UTC by eugenpogodin

2019-09-17 18:25 UTC, anton-kochev requested changes
List of players in `squad.md` should be provided in the alphabetical order

2019-09-17 18:26 UTC, anton-kochev requested changes
Player's first and last name should be in Ukrainian

2019-09-17 18:31 UTC, anton-kochev requested changes
Please check the photos requirements!

These photos are not appropriate:
players/bogdanov.andrey.19850203.png
players/dmitruk.dima.19960723.png
players/dubina.nikita.19980114.png
players/krasavin.artem.19969411.jpg
players/shok.sergey.19891129.png
players/trotsenko.dmitriy.19830201.png
players/zakabluka.anatolii.19930811.png

2019-09-17 18:33 UTC, anton-kochev requested changes
Please correct the content of squad.md

2019-09-17 18:33 UTC, anton-kochev commented on applications/keyua/squad.md
> +`9` [**Красавин** Артем](/players/krasavin.artem.19969411.jpg) `/1996-04-11/`
Birthdate in filename doesn't match the birthdate after. Please fix it

2019-09-17 18:33 UTC, anton-kochev commented on applications/keyua/squad.md
> +`27` [**Корниенко** Леонид](/players/kornienko.leonid.19910124.jpg) `/1991-01-23/`
Birthdate in filename doesn't match the birthdate after. Please fix it

2019-09-18 15:40 UTC, steamhammer requested changes
Троценко, Дубина, Зеленый - игроки, которые были заявлены за команду из Суперлиги городского чемпионата (https://fdo.dp.ua/team/dwt). Согласно Регламенту они считаются игроками-профи. Таких в заявке может быть не больше 2.

ПриватБанк не считается ИТ-предприятием.

2019-09-18 15:48 UTC, eugenpogodin commented
С приватом ок, можете его не заявлять. С заявки убирать не будем никого больше.
Дубина ок, согласен
Зелёный уже играл в турнире за ялантис, не хочу чтобы наши же сотрудники из-за ваших правил не могли играть за свою команду, но спокойно за противника
Троценко вратарь команды. Он 2 года вообще в футбол не играл, у него проблемы с коленями, в заявке двт он как помощник и все.
У нас все в штате, без легионеров и команду итак ели собрали. Убирать никого не будем. Прошу пересмотрите ситуацию, либо же пусть остальные команды голосуют заявлять нас или нет
Sent from my iPhone

> On 18 Sep 2019, at 18:40, Oleksandr Tkalenko <notifications@github.com> wrote:
> 
> ﻿
> @steamhammer requested changes on this pull request.
> 
> Троценко, Дубина, Зеленый - игроки, которые были заявлены за команду из Суперлиги городского чемпионата (https://fdo.dp.ua/team/dwt). Согласно Регламенту они считаются игроками-профи. Таких в заявке может быть не больше 2.
> 
> ПриватБанк не считается ИТ-предприятием.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-18 16:28 UTC, anton-kochev commented on applications/keyua/squad.md
> +
Нужно удалить все лишние строки

2019-09-18 16:51 UTC, anton-kochev requested changes

2019-09-18 16:51 UTC, anton-kochev commented on applications/keyua/squad.md
> +`1` [**Троценко** Дмитрій](/players/trotsenko.dmitriy.19830201.jpg) `/1983-02-01/`
Имя с опечаткой

2019-09-18 16:51 UTC, anton-kochev commented on applications/keyua/squad.md
> +`12` [**Дмитрук** Дмитрій](/players/dmitruk.dima.19960723.jpg) `/1996-07-23/`
Имя с опечаткой

2019-09-18 16:51 UTC, anton-kochev commented on applications/keyua/squad.md
> +`27` [**Корнієнко** Леонід](/players/kornienko.leonid.19910124.jpg) `/1991-01-23/`
День рождения не совпадает с частью имени файла

2019-09-18 16:51 UTC, anton-kochev commented on applications/keyua/squad.md
> +`9` [**Красавін** Артем](/players/krasavin.artem.19969411.jpg) `/1996-04-11/`
День рождения не совпадает с частью имени файла

2019-09-18 16:51 UTC, anton-kochev commented on applications/keyua/squad.md
> +`21` [**Снісаревський** Олег](/players/snisarevskiy.oleg.19910708.jpg) `/1996-08-26/` PrivatBank
Игрок не допущен

2019-09-18 18:12 UTC, eugenpogodin commented on applications/keyua/squad.md
> +`1` [**Троценко** Дмитрій](/players/trotsenko.dmitriy.19830201.jpg) `/1983-02-01/`
в чем опечатка?

2019-09-19 11:03 UTC, anton-kochev requested changes
Все фотографии должны быть в формате `jpeg`

2019-09-19 11:04 UTC, anton-kochev commented on applications/keyua/squad.md
> +`1` [**Троценко** Дмитрій](/players/trotsenko.dmitriy.19830201.jpg) `/1983-02-01/`
В украинском нет имени Дмитрій, но есть Дмитро

2019-09-20 20:38 UTC, steamhammer submitted a review, later dismissed
Снисаревский Олег не допущен.
Игрок Зеленый Антон допущен к соревнованиям. С него снято звание футболиста-профи, 
ограничивающее участия игрока в соревнованиях  IT-league.
 По остальному составу вопросов нет.

2019-09-24 08:17 UTC, anton-kochev requested changes
Фотография Троценко отсутствует

2019-09-24 12:40 UTC, anton-kochev commented
Заявочные документы приняты.
Фтографии приняты.

2019-09-24 12:41 UTC, anton-kochev approved these changes

2019-09-24 12:41 UTC, merged