Ciklum initial info
football-it-league-dnipro/football-it-dp-ua pull request #12
Opened 2019-09-17 11:29 UTC by OleksiiKipra

2019-09-17 11:41 UTC, steamhammer requested changes
1. Именование файлов с фото должно быть латиницей
2. Фоточки нужно сливать в общую папку `applications/players`

2019-09-18 09:44 UTC, anton-kochev requested changes
Нужно обновить заявку с номерами на сезон. Да, они не обязательно могут совпадать с номерами на футболках.

2019-09-18 09:44 UTC, anton-kochev commented on applications/ciklum/squad.md
> +`` [**Вонсаровський** Сергій](/players/vonsarovskii.sergii.19870227.jpg) `/1983-10-01/`
Не совпадает день рождения с частью имени файла

2019-09-18 10:21 UTC, OleksiiKipra commented
> Нужно обновить заявку с номерами на сезон. Да, они не обязательно могут совпадать с номерами на футболках.

завтра заполню номера, когда люди определятся кому какой размер формы подходит

2019-09-20 09:01 UTC, anton-kochev requested changes

2019-09-20 09:01 UTC, anton-kochev commented on applications/ciklum/squad.md
> +`88` [**Шинкаренко** Денис](/players/shynkarenko.denys.19840902.jpg) `/1984-09-02/` Erbis
Точное название компании *Erbis Cloud Services*

2019-09-20 09:01 UTC, anton-kochev commented on applications/ciklum/squad.md
> +`99` [**Матвєєв** Олександр](/players/matveev.oleksandr.19901206.jpg) `/1990-12-06/` PnwSoft
Не нашел информации о компании *PnwSoft*
Если можно, пожалуйста, одну-две ссылки

2019-09-20 09:03 UTC, anton-kochev requested changes

2019-09-20 09:03 UTC, anton-kochev commented on applications/ciklum/squad.md
> +https://www.ciklum.com
Нужно обавить одну-две ссылки на Днепровский офис компании

2019-09-20 09:04 UTC, anton-kochev commented
Фотографии приняты

2019-09-20 11:04 UTC, OleksiiKipra commented on applications/ciklum/squad.md
> +https://www.ciklum.com
сайт общих для всех офисов. Днерповский офис указан в контактах на сайте.
есть на сайте описание Днепровского описа в разделе вакансий: https://jobs.ciklum.com/offices/dnipro/
так же есть неофициальная страница https://www.facebook.com/pages/Ciklum-Dnipro/968522649969651
которая ссылается на https://www.ciklum.com
официальная страница Ciklum в fb: https://www.facebook.com/ciklum/
но, опять же, на все офисы сразу.
что из этого всего надо добавить в файл?

2019-09-20 11:05 UTC, OleksiiKipra commented on applications/ciklum/squad.md
> +https://www.ciklum.com
есть еще тег в инстаграм:
https://www.instagram.com/explore/tags/ciklum_dp/

2019-09-20 11:12 UTC, OleksiiKipra commented on applications/ciklum/squad.md
> +`99` [**Матвєєв** Олександр](/players/matveev.oleksandr.19901206.jpg) `/1990-12-06/` PnwSoft
https://www.pnwsoft.com/
https://rabota.ua/company1777393
https://www.work.ua/jobs/by-company/412010/#about-company

2019-09-20 12:00 UTC, anton-kochev commented on applications/ciklum/squad.md
> +https://www.ciklum.com
Эту пожалуйста
https://jobs.dou.ua/companies/ciklum/

2019-09-20 12:01 UTC, anton-kochev commented on applications/ciklum/squad.md
> +`99` [**Матвєєв** Олександр](/players/matveev.oleksandr.19901206.jpg) `/1990-12-06/` PnwSoft
Спасибо. Нужно исправить тогда на Pacific Northwest Software

2019-09-20 13:00 UTC, anton-kochev commented
Заявочная документация принята

2019-09-20 13:00 UTC, anton-kochev approved these changes

2019-09-20 20:46 UTC, steamhammer approved these changes
По составу вопросов нет.

2019-09-20 20:46 UTC, merged