registration: reactor
football-it-league-dnipro/football-it-dp-ua pull request #13
Opened 2019-09-17 12:18 UTC by AndreyStepanenko

2019-09-20 20:48 UTC, steamhammer requested changes
По составу вопросов нет.
Нужна недостающая фотка Стасюка Сергея

2019-09-20 20:48 UTC, steamhammer commented on applications/reactor/reactor.md
> +`9` **Стасюк** Сергій `/1994-07-19/`
Не хватает фоточки Стасюка

2019-09-22 06:37 UTC, anton-kochev reviewed
Заявка принята. Фотографии приняты

2019-09-24 15:07 UTC, anton-kochev approved these changes

2019-09-24 15:09 UTC, steamhammer approved these changes
👍

2019-09-24 15:10 UTC, merged