registration: Solvve
football-it-league-dnipro/football-it-dp-ua pull request #16
Opened 2019-09-17 19:57 UTC by ShepetaAndrey

2019-09-20 20:59 UTC, steamhammer requested changes
Необходимо подтеврждение по игроку Иванков Евгений.

Просьба все имена переписать на украинском языке, транслитерацию имен на латинице сделать тоже из украинского.

2019-09-20 20:59 UTC, steamhammer commented on applications/solvve/squad.md
> +[**Иванков** Евгений](/players/ivankov.eugene.19920720.jpg) `/1992-07-20/`
Необходимо подтверждение, что данный игрок является сотрудником компании Solvve

2019-09-20 21:04 UTC, steamhammer requested changes

2019-09-20 21:04 UTC, steamhammer commented on applications/solvve/squad.md
> +[**Москаленко** Дмитрий](/players/moskalenko.dmitriy.19900129.jpg) `/1990-01-29/` UENI
Необходимо больше информации о компании UENI

2019-09-22 06:20 UTC, anton-kochev requested changes
- Номера игроков должны быть указаны
- Фото требуют доработки:
   - dmytrenko.roman.19940715
   - lagynovsky.alexey.19960208
   - lypnyagov.nikita.19990406
   - oleynyk.dmytriy.19920603

2019-09-22 06:20 UTC, anton-kochev commented on applications/solvve/squad.md
> +
Лишняя пустая строка

2019-09-22 06:20 UTC, anton-kochev commented on applications/solvve/squad.md
> +[**Марченко** Андрей](/players/marchenko.andrey.19900724.jpg) `/1999-07-24/` Owox
не совпадает день рождения и часть в имени файла

2019-09-22 06:20 UTC, anton-kochev commented on applications/solvve/squad.md
> +#Solvve
пробел после `#`

2019-09-22 21:11 UTC, steamhammer approved these changes

2019-09-22 21:11 UTC, steamhammer commented
По игрокам вопросов нет

2019-09-22 21:25 UTC, anton-kochev commented
Заявочные документы приняты.
Фотографии приняты.

2019-09-22 21:26 UTC, anton-kochev approved these changes

2019-09-22 21:26 UTC, merged

2019-09-23 17:14 UTC, ShepetaAndrey commented
В заявке отсутствует один из наших игроков. Можно как-то добавить его?