Registration/soft serve.2
football-it-league-dnipro/football-it-dp-ua pull request #17
Opened 2019-09-18 05:48 UTC by zlobin-oleksii

2019-09-19 16:52 UTC, anton-kochev requested changes
- Список игроков в алфавитном порядке, пожалуйста
- Фамилия имя на украинском, пожалуйста
- Имена файлов в нижнем регистре, пожалуйста
- Все фотографии в формате `jpg`, пожалуйста

Фотографии неподходящего качества:
players/Galjas.Jurij.19890802.png
players/Karpenko.Denis.19960610.jpg
players/Kolesnik.Nikolaj.19920615.jpg
players/Mihajlov.Stepan.19891102.png
players/Novoselov.Sergej.19851102.jpg
players/Zlobin.Aleksej.19910605.jpg

2019-09-19 16:52 UTC, anton-kochev commented on applications/SoftServe.2/squad.md
> +[**Галяс** Юрий](/players/Galjas.Jurij.19890802.png) `/1989-08-02/` Wix
Должна быть пустая строка между строками
\+ [**Ивлиев** Андрей](/players/Ivliev.Andrej.19910227.jpg) `/1991-02-27/` DevLineSoft
\+
\+[**Карпенко** Денис](/players/Karpenko.Denis.19960610.jpg) `/1996-06-10/`

2019-09-20 14:10 UTC, anton-kochev requested changes

2019-09-20 14:10 UTC, anton-kochev commented on applications/SoftServe.2/squad.md
> +[**Івліев** Андрій](/players/ivliiev.andrii.19910227.jpg) `/1991-02-27/` DevLineSoft
Речь идет о https://youcontrol.com.ua/catalog/company_details/42215086/ ?
Не нашел информации о компании. Если можно одну-две ссылки на источник с информацией.

2019-09-20 14:10 UTC, anton-kochev commented on applications/SoftServe.2/squad.md
> +[**Михайлов** Степан](/players/mykhailov.stepan.19891102.jpg) `/1989-11-02/` Runple
Не нашел информации о компании _Runple_. Если можно одну-две ссылки на источник с информацией.

2019-09-20 14:18 UTC, anton-kochev requested changes

2019-09-20 14:18 UTC, anton-kochev commented on applications/SoftServe.2/squad.md
> +https://www.softserveinc.com
Добавьте, пожалуйста, одну две ссылки на офис(ы) в Днепре (DOU, LinkedIn и т.п.)

2019-09-23 06:48 UTC, zlobin-oleksii commented on applications/SoftServe.2/squad.md
> +[**Михайлов** Степан](/players/mykhailov.stepan.19891102.jpg) `/1989-11-02/` Runple
https://runple.com/
https://www.linkedin.com/company/runple/about/
https://jobs.dou.ua/companies/runple/offices/

2019-09-23 07:10 UTC, zlobin-oleksii commented on applications/SoftServe.2/squad.md
> +[**Івліев** Андрій](/players/ivliiev.andrii.19910227.jpg) `/1991-02-27/` DevLineSoft
да

2019-09-23 08:31 UTC, anton-kochev requested changes
Необходимо указать номера в заявке

2019-09-23 09:47 UTC, anton-kochev requested changes
Нужны фотографии подходящего качества для: Ермаков и Злобин

2019-09-23 09:55 UTC, zlobin-oleksii commented
@anton-kochev можно пожалуйста, показать критерии оценки качества фото?

2019-09-23 10:01 UTC, anton-kochev commented
> @anton-kochev можно пожалуйста, показать критерии оценки качества фото?

https://github.com/football-it-league-dnipro/football-it-dp-ua/blob/master/applications/guide.md#%D0%B7%D0%B0%D0%B2%D0%B0%D0%BD%D1%82%D0%B0%D0%B6%D0%B8%D1%82%D0%B8-%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D1%96%D1%97

2019-09-23 12:22 UTC, anton-kochev approved these changes
Заявочная документация принята.
Фотографии приняты.

2019-09-23 12:23 UTC, anton-kochev commented
@steamhammer можно проверять состав

2019-09-23 14:53 UTC, steamhammer commented
По составу вопросов нет

2019-09-23 14:53 UTC, merged