Registration: Agilie
football-it-league-dnipro/football-it-dp-ua pull request #20
Opened 2019-09-19 10:46 UTC by savilov

2019-09-20 09:16 UTC, anton-kochev requested changes
Список игроков должен быть в алфавитном порядке

Имя файла фотграфии игрока должно быть в формате `lastname.firstname.birthdate.jpg` 
`players/yevhen.kovalenko.19870519.jpg`

2019-09-20 09:16 UTC, anton-kochev commented on applications/agilie/squad.md
> +`29` [**Гоцко** Стас](/players/gotsko.stas.19930528.jpg) `/1993-05-28/` WizardDev
Скорее всего правильно **Станіслав**

2019-09-20 09:17 UTC, anton-kochev commented
Фотографии приняты

2019-09-20 09:59 UTC, anton-kochev requested changes

2019-09-20 09:59 UTC, anton-kochev commented on applications/agilie/squad.md
> +`29` [**Гоцко** Станіслав](/players/gotsko.stanislav.19930528.jpg) `/1993-05-28/` WizardDev
Правильное название компании **WizardsDev**, если я не ошибаюсь

2019-09-20 09:59 UTC, anton-kochev commented
Заявочные материалы приняты

2019-09-20 10:00 UTC, anton-kochev commented
@steamhammer Нужно провести процедуру допуска

2019-09-20 10:04 UTC, anton-kochev approved these changes

2019-09-23 19:36 UTC, steamhammer commented
Вопросов по составу нет.

2019-09-23 19:36 UTC, steamhammer approved these changes

2019-09-23 19:37 UTC, merged