created squad.md
football-it-league-dnipro/football-it-dp-ua pull request #23
Opened 2019-09-20 15:54 UTC by kstanislav

2019-09-20 16:09 UTC, steamhammer requested changes
- Необходимо добавить фото каждого игрока.
- Состав необходимо отформатировать согласно требованиям изложенным в гайде https://github.com/football-it-league-dnipro/football-it-dp-ua/blob/master/applications/guide.md

2019-09-22 05:47 UTC, anton-kochev requested changes

2019-09-22 05:47 UTC, anton-kochev commented on applications/yalantis/squad.md
> +`8` **Малий** Евген `/1997-03-07/` Webland Digital Agency
Нужно больше информации о **Webland Digital Agency**

2019-09-23 05:24 UTC, anton-kochev commented
Малому Евгению отказано в допуске к соревнованиям

2019-09-24 14:53 UTC, anton-kochev requested changes
Нужно исправить заявку
Нужны другие фотографии:
players/suprun.mykola.19891221.jpg
players/lynnik.vladislav.19931202.jpg
players/chernysh.vitaliy.19970520.jpg

2019-09-24 14:53 UTC, anton-kochev commented on applications/yalantis/squad.md
> +`2` [**Козирев** Станiслав](/players/kozyrev.stanislav.19090808.jpg) `/1990-08-08/`
Нужно исправить имя файла - не совпадает с датой рождения

2019-09-24 14:53 UTC, anton-kochev commented on applications/yalantis/squad.md
> +`29` [**Крижановський** Антон](/players/kryzhanovkyi.anton.19872002.jpg) `/1987-02-20/` Valtech
Имя файла не совпадает с датой рождения

2019-09-25 07:53 UTC, anton-kochev approved these changes
Документация и фотографии приняты

2019-09-26 09:23 UTC, steamhammer approved these changes

2019-09-26 09:24 UTC, merged