Go Wombat Team Application 2019
football-it-league-dnipro/football-it-dp-ua pull request #27
Opened 2019-09-23 16:11 UTC by dmitrysus

2019-09-23 19:47 UTC, steamhammer commented on applications/go.wombat.team/squad.md
> +`26` [**Козаков** Денис](/players/kozakov.denys.19920824.jpg) `/1992-08-24/`
Необходимо дополнительное подтверждение по игроку Козаков Денис

2019-09-24 09:22 UTC, steamhammer commented on applications/go.wombat.team/squad.md
> +`77` [**Палій** Вадим](/players/palii.vadym.19980112.jpg) `/1998-01-12/`
Необходимо дополнительное подтверждение по игроку Палий Вадим

2019-09-24 14:17 UTC, steamhammer submitted a review, later dismissed
Вопросов по составу нет.
Состав принят. 👍

2019-09-24 15:06 UTC, anton-kochev requested changes
Список игроков должен быть в алфавитном порядке

2019-09-24 15:06 UTC, anton-kochev commented
Фотографии приняты

2019-09-25 20:45 UTC, anton-kochev approved these changes
Заявочные документы приняты

2019-09-26 06:58 UTC, merged