Registration: Gloria FX
football-it-league-dnipro/football-it-dp-ua pull request #4
Opened 2019-09-16 20:04 UTC by kate-dzi

2019-09-17 16:23 UTC, anton-kochev reviewed
Please provide another photo for `players/dzihovskyi.andrij.19880324.jpg`. The face is not well recognizable

2019-09-17 16:23 UTC, anton-kochev commented on applications/gloria.fx/squad.md
> +`44` [**Бєлiзной** Андрiй](/players/beliznoy.andrei.19950604.jpg) `/1995-06-04/`
A newline is missing between lines.
Should be:

\+ `44` [**Бєлiзной** Андрiй](/players/beliznoy.andrei.19950604.jpg) `/1995-06-04/`
\+
\+ `4` [**Боговенко** Олег](/players/bohovenko.oleh.19891111.jpg) `/1989-11-11/`

2019-09-17 16:23 UTC, anton-kochev commented on applications/gloria.fx/squad.md
> +https://gloriafx.com/
Please add also this link https://www.facebook.com/gloriafx and DOU (if you have)

2019-09-17 16:51 UTC, kate-dzi commented on applications/gloria.fx/squad.md
> +https://gloriafx.com/
Should I add links to the same line separated by commas?

2019-09-17 17:24 UTC, anton-kochev commented on applications/gloria.fx/squad.md
> +https://gloriafx.com/
Each link on the separate line, please

2019-09-17 17:25 UTC, anton-kochev reviewed
See comments above

2019-09-17 18:02 UTC, anton-kochev requested changes
Please fix all issues

2019-09-18 09:32 UTC, anton-kochev commented
@steamhammer Documentation approved. Players check to be performed

2019-09-18 10:44 UTC, steamhammer commented
> @steamhammer Documentation approved. Players check to be performed

All good

2019-09-18 10:45 UTC, steamhammer approved these changes
all good

2019-09-18 13:03 UTC, anton-kochev approved these changes

2019-09-18 13:05 UTC, merged