Update squad.md
football-it-league-dnipro/football-it-dp-ua pull request #48
Opened 2020-03-07 17:17 UTC by osaula9

2020-03-08 19:41 UTC, anton-kochev requested changes
Не хватает фотографий вновь заявленных участников

2020-03-09 09:19 UTC, osaula9 commented
Не дает залить фото новых игроков, пишет что нет доступа у меня

2020-03-09 09:23 UTC, osaula9 commented
Закину сюда, можешь перенести или дать мне доступ, чтобы мог залить, спасибо
![ilyev igor 19870518](https://user-images.githubusercontent.com/53176825/76199355-5f7c8080-61f8-11ea-9d28-7c531198daf9.jpg)
![kiselov dmytro 19930126](https://user-images.githubusercontent.com/53176825/76199359-60adad80-61f8-11ea-8ce8-2a82119bfc40.jpg)

2020-03-09 10:57 UTC, anton-kochev commented
Как понять где кто?

2020-03-09 11:01 UTC, osaula9 commented
Фото подписаны по всем стандартам, если что Ильев верхнее фото, Киселев нижнее.

2020-03-09 13:03 UTC, anton-kochev approved these changes
Не хватает фотографий вновь заявленных участников

2020-03-11 14:52 UTC, steamhammer approved these changes

2020-03-11 20:12 UTC, merged