noosphere team's application
football-it-league-dnipro/football-it-dp-ua pull request #5
Opened 2019-09-17 07:16 UTC by yury-moiseev

2019-09-17 17:17 UTC, anton-kochev reviewed
Please provide another photo for
`players/mikitenko.artem.19870701.jpg`
`players/safonov.leonid.19980625.jpg`
`players/studenov.oleg.19931013.jpg`
They do not meet the requirements

2019-09-17 17:17 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Черненко** Роман](/players/chernenko.roman.19950307.jpg) `/1995-03-07/`
Please use the Ukrainian language for the first and last name

2019-09-17 17:18 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Черненко** Роман](/players/chernenko.roman.19950307.jpg) `/1995-03-07/`
Use transliterated from the Ukrainian language for the file name

2019-09-17 18:18 UTC, anton-kochev requested changes
Please check the place you started your branch.
Excess changes are present in this pull-request.

2019-09-20 09:33 UTC, anton-kochev requested changes
Необходимо указать номер игрока на сезон. Да, он может не совпадать с номером на игру

В `pull request` все еще присутствуют ненужные изменения:
README.md
applications/guid.md
applications/readme.md
documents-and-regulations/competition-regulations.md

2019-09-20 09:33 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Коростюк** Кирилло](/players/korostiuk.kirillo.19940510.png) `/1994-05-10/`
Опечатка **Кирило**
В имени файла тоже

2019-09-20 09:33 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Горобець** Сергiй](/players/gorobets.sergey.19900921.jpg) `/1990-09-21/`
`sergii` в имени файла

2019-09-20 09:33 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Коростюк** Кирилло](/players/korostiuk.kirillo.19940510.png) `/1994-05-10/`
Формат файла должен быть `jpg`

2019-09-20 09:33 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Дімітракі** Андрій](/players/dimitraki.andrii.19920302.jpg) `/1992-03-02/` Allo
Точное название компании **Алло** если я не ошибаюсь

2019-09-20 09:35 UTC, anton-kochev commented
Фотографии приняты

2019-09-23 12:19 UTC, alexeypodolian commented on applications/noosphere/noosphere.md
> +`w/n` [**Дімітракі** Андрій](/players/dimitraki.andrii.19920302.jpg) `/1992-03-02/` Allo
**Алло** - это IT компания?

2019-09-23 16:39 UTC, steamhammer commented
По составу вопросов нет.

2019-09-23 20:21 UTC, anton-kochev commented on applications/noosphere/noosphere.md
> +`w/n` [**Дімітракі** Андрій](/players/dimitraki.andrii.19920302.jpg) `/1992-03-02/` Allo
@alexeypodolian Нет, но мы идем на встречу ребятам, которые давно заиграны в соревнованиях

2019-09-24 07:56 UTC, anton-kochev requested changes
Не нужно ничего удалять!
Сделайте _rebase_ или создайте новый _pull request_

2019-09-24 22:12 UTC, closed without merging