registration: ardas group inc.
football-it-league-dnipro/football-it-dp-ua pull request #6
Opened 2019-09-17 07:25 UTC by osaula9

2019-09-17 17:45 UTC, anton-kochev reviewed
Please provide another photo for
`players/gaytsuk.edgar.19880815.jpg`
`players/kuprianenko.volodymyr.19910312.jpg`
`players/vovchenko.oleksiy.19910706.jpg`

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +Склад команди:
This line is not needed. Please remove

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`8`	 [**Борисов** Ігорь](/players/borysov.igor.19950605.jpg)	`/1995-06-05/`
Please use a single whitespace symbol (instead of tabulation) as a separator between number, name, birth date and company name

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`11` [**Ретізник** Ігорь](/players/retiznik.igor.19920120.jpg) `/1992-01-20/`
Name is in Russian

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`13` [**Жарко** Роман](/players/zharko.roman.19810412.jpg)	`/1987-01-19/`
Birthdate in filename doesn't match the birthdate after. Please fix it

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`99` [**Вовченко** Олексій](/players/vovchenko.oleksiy.19910706.jpg) `/1991-07-16/`
Birthdate in filename doesn't match the birthdate after. Please fix it

2019-09-17 17:45 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`3`  [**Лупирь** Артем](/players/lupyr.artem.19871504.jpg) `/1987-04-15/`
Birthdate in filename doesn't match the birthdate after. Please fix it

2019-09-17 18:19 UTC, anton-kochev requested changes
Please check the place you started your branch.
Excess changes are present in this pull-request.

2019-09-18 08:35 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`8`	 [**Борисов** Ігорь](/players/borysov.igor.19950605.jpg)	`/1995-06-05/`
@osaula9 Still an issue. Tabulations are present

2019-09-19 10:54 UTC, anton-kochev requested changes

2019-09-19 10:54 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +https://ardas-it.com/
Пожалуйста, добавьте больше информации о Днепровском офисе компании (DOU, Facebook и т.п.)

2019-09-19 10:58 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +https://ardas-it.com/
В `pull request` все еще присутствуют избыточные изменение

2019-09-20 14:36 UTC, anton-kochev requested changes

2019-09-20 14:36 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +https://jobs.dou.ua/companies/ardas-group/
Символ `newline` нужен между ссылками. Чтобы каждая ссылка была на новой строке в отформатированном виде.

2019-09-20 14:39 UTC, anton-kochev requested changes

2019-09-20 14:39 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`12` [**Болонський** Олексій](/players/bolonskiy.oleksiy.19860522.jpg)	`/1986-05-22/`
В качестве разделителя нужно использовать пробел, а не табуляцию.
В конце строки пробелов быть не должно

2019-09-20 14:39 UTC, anton-kochev commented on applications/ardas.group.inc/squad.md
> +`1` [**Іванов** Олександр](/players/ivanov.oleksandr.19970509.jpg) `/1997-05-09/` EnglishDom
Не нашел информации о компании, подтверждающей ее `IT` профиль

2019-09-21 13:39 UTC, osaula9 commented on applications/ardas.group.inc/squad.md
> +`1` [**Іванов** Олександр](/players/ivanov.oleksandr.19970509.jpg) `/1997-05-09/` EnglishDom
https://jobs.dou.ua/companies/englishdom/,  EnglishDom — онлайн-школа английского языка, один из лидеров EdTech в Восточной Европе со штаб-квартирой в Днепре.

2019-09-21 14:40 UTC, anton-kochev commented
Заявочная документация принята

2019-09-21 14:40 UTC, anton-kochev commented
Фотографии приняты

2019-09-23 08:33 UTC, anton-kochev commented
@steamhammer по составу еще остались вопросы?

2019-09-23 08:33 UTC, anton-kochev approved these changes

2019-09-23 11:21 UTC, steamhammer commented on applications/ardas.group.inc/squad.md
> +`7` [**Оріховський** Станіслав](/players/orekhovskiy.stanislav.19890501.jpg) `/1989-05-01/`
Нужно дополнительное подтверждение по Ореховскому Станиславу

2019-09-23 11:21 UTC, steamhammer commented on applications/ardas.group.inc/squad.md
> +`3` [**Лупирь** Артем](/players/lupyr.artem.19870415.jpg) `/1987-04-15/`
Нужно дополнительное подтверждение по Лупырю Артему

2019-09-23 11:21 UTC, steamhammer commented on applications/ardas.group.inc/squad.md
> +`6` [**Купріяненко** Володимир](/players/kuprianenko.volodymyr.19910312.jpg) `/1991-03-12/`
Нужно дополнительное подтверждение по Куприяненко Владимиру

2019-09-23 11:21 UTC, steamhammer commented on applications/ardas.group.inc/squad.md
> +`8` [**Борисов** Ігор](/players/borysov.igor.19950605.jpg) `/1995-06-05/`
Нужно дополнительное подтверждение по Борисову Игорю

2019-09-23 12:10 UTC, steamhammer commented
По составу вопросов нет. Все подтверждения получены.

2019-09-23 12:10 UTC, merged